#!/usr/bin/env python3
import os
import sys
import numpy as np
from PIL import Image

# ================= CONFIGURATION =================
# 1. INPUT MASKS: The folder containing your new PNG masks
# MAKE SURE this folder contains .png files (generated by gt_binary.py)
MASK_DIR = r"/mnt/d/Rana Muhammad Adeel/Final Year Project/Final_Year_Project/Hard_Exudates_Segmentation/Processed_Data/Hard_Exudates_Masks"

# 2. INPUT ORIGINALS: PATH TO YOUR COLORED FUNDUS IMAGES
# Point this to where IDRiD_01.jpg, IDRiD_02.jpg are located.
DATA_DIR = r"/mnt/d/Rana Muhammad Adeel/Final Year Project/Segmentation/A. Segmentation/1. Original Images/a. Training Set"

# 3. OUTPUT: Where to save the patches
OUTPUT_PATCHES_DATA = r"/mnt/d/Rana Muhammad Adeel/Final Year Project/Final_Year_Project/Hard_Exudates_Segmentation/Processed_Data/Patches/Images"
OUTPUT_PATCHES_MASK = r"/mnt/d/Rana Muhammad Adeel/Final Year Project/Final_Year_Project/Hard_Exudates_Segmentation/Processed_Data/Patches/Masks"
# 4. PATCH SETTINGS
PATCH_SIZE = 512
STRIDE = 256  # Overlap of 50% (512/2) to catch lesions at edges
# =================================================

def create_dirs():
    if not os.path.exists(OUTPUT_PATCHES_DATA):
        os.makedirs(OUTPUT_PATCHES_DATA)
    if not os.path.exists(OUTPUT_PATCHES_MASK):
        os.makedirs(OUTPUT_PATCHES_MASK)

def extract_patches():
    negative_patches = [] # To track background-only patches
    positive_count = 0
    total_processed = 0

    # Get list of original images (JPG or TIF)
    files = [f for f in os.listdir(DATA_DIR) if f.lower().endswith(('.jpg', '.jpeg', '.tif', '.tiff'))]
    files.sort()

    print(f"Found {len(files)} original images. Starting extraction...")

    for file in files:
        # 1. READ IMAGE
        img_path = os.path.join(DATA_DIR, file)
        
        # 2. READ MASK (Looking for .png version)
        # Assumes file is "IDRiD_01.jpg", looking for "IDRiD_01.png"
        mask_name = os.path.splitext(file)[0] + "_EX.png"
        mask_path = os.path.join(MASK_DIR, mask_name)
        
        if not os.path.exists(mask_path):
            print(f"⚠️ Skipping {file}: Mask not found at {mask_path}")
            continue

        try:
            image = Image.open(img_path).convert("RGB")
            mask = Image.open(mask_path).convert("L") # Grayscale
        except Exception as e:
            print(f"❌ Error opening {file}: {e}")
            continue

        # Ensure Mask and Image are same size (sometimes IDRiD differs by 1 pixel)
        if image.size != mask.size:
            mask = mask.resize(image.size, Image.NEAREST)

        w, h = image.size
        
        # --- SLIDING WINDOW LOOP ---
        patch_id = 0
        file_id = os.path.splitext(file)[0] # e.g., IDRiD_01

        for y in range(0, h - PATCH_SIZE + 1, STRIDE):
            for x in range(0, w - PATCH_SIZE + 1, STRIDE):
                
                # Crop Patch
                box = (x, y, x + PATCH_SIZE, y + PATCH_SIZE)
                img_patch = image.crop(box)
                mask_patch = mask.crop(box)

                # Check if patch is useful (Not mostly black background)
                # Convert to numpy to check pixel values
                mask_array = np.array(mask_patch)
                img_array = np.array(img_patch)

                # Skip if the image patch is 95% black (outside the eye circle)
                if np.mean(img_array) < 10: 
                    continue 

                # Define Filename (Always PNG)
                save_name = f"{file_id}_p{patch_id}.png"

                # Save Data
                # Note: Saving image as PNG is safer for training, though JPG is smaller.
                # Since you want high quality, we use PNG.
                try:
                    img_patch.save(os.path.join(OUTPUT_PATCHES_DATA, save_name), "PNG")
                    mask_patch.save(os.path.join(OUTPUT_PATCHES_MASK, save_name), "PNG")

                    # Classification: Is this patch Positive (Has Lesion) or Negative?
                    if np.sum(mask_array) > 0: 
                        positive_count += 1
                    else:
                        negative_patches.append(save_name)

                    patch_id += 1
                except Exception as e:
                    print(f"Error saving patch {save_name}: {e}")

        total_processed += 1
        print(f"Processed: {file} | Pos Patches: {positive_count} | Neg Patches: {len(negative_patches)}", end='\r')

    print(f"\n\nExtraction Done.")
    print(f"Total Positive Patches (Lesions): {positive_count}")
    print(f"Total Negative Patches (Background): {len(negative_patches)}")

    # === DATASET BALANCING ===
    # Logic: Keep negative patches equal to 3x the positive patches
    # This prevents the dataset from being 99% empty background.
    
    target_negatives = 3 * positive_count
    
    if len(negative_patches) > target_negatives:
        delete_count = len(negative_patches) - target_negatives
        print(f"⚖️ Balancing: Deleting {delete_count} excess background patches...")
        
        neg_arr = np.array(negative_patches)
        np.random.shuffle(neg_arr)
        to_delete = neg_arr[:delete_count]

        for name in to_delete:
            try:
                os.remove(os.path.join(OUTPUT_PATCHES_MASK, name))
                os.remove(os.path.join(OUTPUT_PATCHES_DATA, name))
            except OSError as e:
                print(f"Error deleting {name}: {e}")
        
        print("✅ Balancing Complete.")
    else:
        print("✅ Data is balanced (Negatives < 3x Positives). No deletion needed.")

if __name__ == "__main__":
    create_dirs()
    extract_patches()